Repository fei-protocol/fei-protocol-core, pull requests merged in 2022-07, with the labels that each got.

#956 Version pcvGuardian, add safe addresses e2e test
  .circleci/config.yml
  protocol-configuration/mainnetAddresses.ts
  protocol-configuration/permissions.ts
  protocol-configuration/safeAddresses.ts
  test/integration/tests/pcv.ts
  test/integration/tests/safeAddresses.ts
Labels: feature

#922 DAO vote 2: Incentives, deprecate PSMs, holding PCV deposits, agEUR redeem
  .circleci/config.yml
  block.txt
  contracts/metagov/DelegatorPCVDeposit.sol
  contracts/metagov/VlAuraDelegatorPCVDeposit.sol
  contracts/pcv/ERC20HoldingPCVDeposit.sol
  contracts/pcv/angle/AngleEuroRedeemer.sol
  contracts/pcv/angle/AngleUniswapPCVDeposit.sol
  contracts/pcv/angle/IAnglePoolManager.sol
  contracts/pcv/angle/IAngleStableMaster.sol
  contracts/pcv/angle/IAngleStakingRewards.sol
  contracts/pcv/angle/IAngleStrategy.sol
  contracts/test/integration/fixtures/MainnetAddresses.sol
  contracts/test/integration/pcv/AngleEuroRedeemer.sol
  contracts/test/integration/pcv/ERC20HoldingPCVDeposit.t.sol
  contracts/test/unit/ERC20HoldingPCVDeposit.t.sol
  proposals/dao/old/pod_exec_v2.ts
  proposals/dao/old/tip_111.ts
  proposals/dao/old/tip_112.ts
  proposals/dao/old/tip_115.ts
  proposals/dao/old/tip_117.ts
  proposals/dao/old/tokemak_withdraw.ts
  proposals/dao/tip_118.ts
  proposals/description/fip_x.ts
  proposals/description/old/pod_exec_v2.ts
  proposals/description/old/tip_111.ts
  proposals/description/old/tip_112.ts
  proposals/description/old/tip_115.ts
  proposals/description/old/tip_117.ts
  proposals/description/old/tokemak_withdraw.ts
  proposals/description/tip_118.ts
  protocol-configuration/collateralizationOracle.ts
  protocol-configuration/mainnetAddresses.ts
  protocol-configuration/pauseState.ts
  protocol-configuration/permissions.ts
  protocol-configuration/proposalsConfig.ts
  protocol-configuration/safeAddresses.ts
  scripts/utils/constructProposalCalldata.ts
  test/integration/tests/balancer-weightedpool.ts
  test/integration/tests/collateralizationOracle.ts
  test/integration/tests/ethPSM.ts
  test/integration/tests/lusdPSM.ts
  test/integration/tests/pauseState.ts
  test/integration/tests/pcv.ts
  test/integration/tests/psm.ts
  test/integration/tests/tribalchief.ts
  test/integration/tests/tribeIncentivesEnd.ts
Labels: devops/process

#957 rename fixture addresses & fix podexecutor unit tests
  contracts/test/integration/governance/RoleBastion.t.sol
  contracts/test/unit/ERC20HoldingPCVDeposit.t.sol
  contracts/test/unit/Fei.t.sol
  contracts/test/unit/NonCustodialPSM.t.sol
  contracts/test/unit/PCVGuardian.sol
  contracts/test/unit/governance/NopeDAO.t.sol
  contracts/test/unit/governance/PodExecutor.t.sol
  contracts/test/utils/Fixtures.sol
Labels: bug

#960 Fix (most) forge compilation warnings
  contracts/mock/MockChainlinkOracle.sol
  contracts/mock/MockConvexBaseRewardPool.sol
  contracts/mock/MockConvexBooster.sol
  contracts/mock/MockCurve3pool.sol
  contracts/mock/MockCurveMetapool.sol
  contracts/mock/MockERC20PCVDeposit.sol
  contracts/mock/MockERC20UniswapPCVDeposit.sol
  contracts/mock/MockEthPCVDeposit.sol
  contracts/mock/MockLendingPool.sol
  contracts/mock/MockMerkleOrchard.sol
  contracts/mock/MockRewardsDistributor.sol
  contracts/mock/MockStEthStableSwap.sol
  contracts/mock/MockStEthToken.sol
  contracts/mock/MockTokemakEthPool.sol
  contracts/mock/MockTokemakRewards.sol
  contracts/mock/MockTribalChief.sol
  contracts/mock/MockVault.sol
  contracts/test/integration/fixtures/MainnetAddresses.sol
  contracts/test/integration/fixtures/Orca.sol
  contracts/test/integration/governance/PodFactory.t.sol
  contracts/test/integration/pcv/ERC20HoldingPCVDeposit.t.sol
  contracts/test/integration/sentinel/FuseWithdrawalGuard.t.sol
  contracts/test/unit/governance/NopeDAO.t.sol
  contracts/test/unit/governance/PodExecutor.t.sol
  contracts/test/utils/StdLib.sol
Labels: devops/process

#949 Add gOHM Oracle, add deposit to CR
  block.txt
  contracts/oracle/GOhmEthOracle.sol
  contracts/test/integration/fixtures/MainnetAddresses.sol
  contracts/test/integration/oracle/GOhmOracleIntegrationTest.t.sol
  contracts/test/unit/oracle/GOhmEthOracle.t.sol
  contracts/test/unit/pcv/ERC20HoldingPCVDeposit.t.sol
  contracts/test/unit/peg/NonCustodialPSM.t.sol
  proposals/dao/old/tip_118.ts
  proposals/dao/tip_119.ts
  proposals/description/old/tip_118.ts
  proposals/description/tip_119.ts
  protocol-configuration/mainnetAddresses.ts
  protocol-configuration/proposalsConfig.ts
  scripts/deploy/migrations.ts
Labels: feature

#976 Sell USDC for DAI
  block.txt
  contracts/external/maker/IDSSPSM.sol
  contracts/test/integration/pcv/AngleEuroRedeemer.sol
  proposals/dao/tip_119.ts
  proposals/description/tip_119.ts
  protocol-configuration/mainnetAddresses.ts
Labels: devops/process

#985 Execute VOLT <> FEI OTC
  block.txt
  proposals/dao/tip_119.ts
  proposals/description/tip_119.ts
  protocol-configuration/collateralizationOracle.ts
  protocol-configuration/mainnetAddresses.ts
Labels: devops/process
